miw_demo:
    resource: "@MiwDemoBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

miw_saludo:
    pattern: /hola
    defaults: { _controller: AppBundle:Saludo:hola }