miw_producto:
    resource: "@MiwDemoBundle/Resources/config/routing_producto.yml"
    prefix:   /producto

miw_demo_persona:
    resource: "@MiwDemoBundle/Resources/config/routing_persona.yml"
    prefix:   /persona

miw_demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: MiwDemoBundle:Default:index }
