miw_producto_nuevo:
    path:     /new
    defaults: { _controller: MiwDemoBundle:Producto:new }

miw_producto_get:
    path:     /{id}.{format}
    defaults: { _controller: MiwDemoBundle:Producto:get,format: html }

miw_producto_getAll:
    path:     /
    defaults: { _controller: MiwDemoBundle:Producto:getAll,format: html }

miw_producto_delete:
    path:     /delete/{id}
    defaults: { _controller: MiwDemoBundle:Producto:delete}
    methods: [POST]
